---
server:
  port: 8090
spring:
  application:
    name: config-server
  cloud:
    config:
      allow-override: true
      fail-fast: true
      override-none: true
      override-system-properties: false
      server:
        git:
          clone-on-start: true
          uri: "https://github.com/Renzo-Espinola/spring-cloud-configuration"
  profiles:
    active: "dev, qa"
  security:
    user:
      name: admin
      password: admin
